#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/consul

- name: Installation of yum-utils, shadow-utils
  yum: 
    name: 
      - yum-utils
      - shadow-utils
    state: present

- name: Add HashiCorp YUM repository
  command: "yum-config-manager --add-repo {{consul_repo_url}}" 
  args:
    creates: "/etc/yum.repos.d/hashicorp.repo"

- name: Install Consul
  yum: 
    name: 
      - "{{ consul_package }}"
    state: present

