---

- name: Install and configure Nomad Servers
  hosts: nomad_server
  become: yes
  roles: 
    - nomad_server

- name: Install and configure Nomad Clients
  hosts: nomad_client
  become: yes
  roles: 
    - nomad_client
